from .yolox_head import YOLOXHeadQ
from .bevformer_head import BEVFormerHeadTRT
from .centernet_head import CenterNetHeadQ
from .centerpoint_head import BEVDetCenterHeadTRT
from .bevformer_occupancy_head_apollo import BEVFormerOccupancyHeadApolloTRT